"""Spark Fuse — Python client library for the Spark Fuse GPU compute API."""
from .client import SparkFuseClient
from .errors import (
    AuthError,
    ForbiddenError,
    NoWarmPoolCapacityError,
    RateLimitError,
    ServiceUnavailableError,
    SessionConflictError,
    SessionError,
    SessionFailedError,
    SessionNotFoundError,
    ShareSyncError,
    SparkFuseError,
    SparkHttpError,
    TokenExpiredError,
)
from .models import (
    AppendJobsResponse,
    CreateJobResponse,
    ErrorCode,
    EstimateResponse,
    InstanceQueue,
    InstanceQueueEntry,
    Job,
    JobStatus,
    LoginResponse,
    LogEvent,
    PreparedInstance,
    QueuedJobRef,
    QueueStatusEvent,
    SESSION_TERMINAL_STATUSES,
    SessionStatus,
    TERMINAL_STATUSES,
    TruncatedEvent,
)

__all__ = [
    "SparkFuseClient",
    # errors
    "AuthError",
    "ForbiddenError",
    "NoWarmPoolCapacityError",
    "RateLimitError",
    "ServiceUnavailableError",
    "SessionConflictError",
    "SessionError",
    "SessionFailedError",
    "SessionNotFoundError",
    "ShareSyncError",
    "SparkFuseError",
    "SparkHttpError",
    "TokenExpiredError",
    # models
    "AppendJobsResponse",
    "CreateJobResponse",
    "ErrorCode",
    "EstimateResponse",
    "InstanceQueue",
    "InstanceQueueEntry",
    "Job",
    "JobStatus",
    "LoginResponse",
    "LogEvent",
    "PreparedInstance",
    "QueuedJobRef",
    "QueueStatusEvent",
    "SESSION_TERMINAL_STATUSES",
    "SessionStatus",
    "TERMINAL_STATUSES",
    "TruncatedEvent",
]
